### ISSUE TITLE
Find() function

### ISSUE THREAD

**Issue by a1cd** [a1cd/Discord-Commands#12]
Create a function that would work well for creating a help command. It would find commands and return the wanted `command`/`cmd` object as well as the command level (0 being the top command and 2 being the subcommand of a subcommand. you get the idea).

**Comment by centanomics** [comment]
Can I be assigned to this issue?

**Comment by a1cd** [comment]
yea!

**Comment by a1cd** [comment]
ok, im going to work on this issue now.

**Comment by a1cd** [comment]
Done!
